nginx:
  build: nginx/
  links:
   - php:php
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - data/www:/var/www/html
   - data/logs:/var/log/nginx
  restart: always
php:
  build: php/
  expose:
   - "9000"
  volumes:
   - data/www:/var/www/html
  restart: always 
